config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  'home#index'
  resources :matter
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord



end

app/models/matter.rb
class Matter < ApplicationRecord

  def user
    return User.find_by(id: self.user_id)
  end

validates :name, presence: true
validates :price, presence: true
validates :category, presence: true
validates :description, presence: true
validates :skill, presence: true

# belongs_to:user

end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :matters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 # ここから追加します
 before_action :configure_permitted_parameters, if: :devise_controller?

 def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name]) # 新規登録時(sign_up時)にnameというキーのパラメーターを追加で許可する
   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name_kana])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name_kana])



 end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
  
end

end

app/controllers/matter_controller.rb
class MatterController < ApplicationController

  before_action :baria_user, only: [:edit, :destroy]
  
  def index
    @matter = Matter.all
  end

  def new
    @matter = Matter.new
  end

  def create
    @matter = Matter.new(matter_params)

    if @matter.save
      redirect_to matter_index_path
    else
      render 'matter/new'
    end
  end

  def show
    @matter = Matter.find(params[:id])
  end

  def edit
    @matter = Matter.find(params[:id])
  end

  def update
    @matter = Matter.find(params[:id])
    @matter.update(matter_params)
    redirect_to matter_index_path
  end

  def destroy
    @matter = Matter.find(params[:id])

    @matter.destroy
    redirect_to request.referer
  end

  private
  def matter_params
    params.require(:matter).permit(:name, :price, :category, :description, :filingday, :skill ).merge(user_id: current_user.id)
  end

  def baria_user
    unless Matter.find(params[:id]).user_id.to_i == current_user.id
        flash[:notice] = "権限がありません"
        redirect_to matter_index_path
    end
   end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/matter_helper.rb
module MatterHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/_aftersign_header.html.erb
<header class = main-header>

  <div class = l-header>
    <h2 class = l-header__logo>エンジニア案件サイト</h2>
  </div>

  <div class = r-header>

    <div class = "r-header__top">
        <form id="form4" action="自分のサイトURL" method="get">
          <input id="sbox4"  id="s" name="s" type="text" placeholder="案件を入力してください" />
          <button id="sbtn4" type="submit">検索</button>
        </form>
    </div>

    <div class = r-header__buttom>
      <li class = r-header__buttom-subitem>
        <%= link_to "マイページ" , '＃', class: "r-header__buttom-subitem-btn" %>
      </li>
      <li class = r-header__buttom-subitem>
        <%= link_to "案件を探す", matter_index_path, class: "r-header__buttom-subitem-btn" %>
      </li>
      <li class = r-header__buttom-subitem>
        <%= link_to "案件投稿", new_matter_path, class: "r-header__buttom-subitem-btn" %>
      </li>
      <li class = r-header__buttom-subitem>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "r-header__buttom-subitem-btn" %>
      </li>
    </div>
  </div>

</header>

app/views/home/_footer.html.erb
<footer class = "footer">
  <h1 class = "footer__text">阿部 隆一朗 ポートフォリオ ECサイト</h1>
</div>

app/views/home/_header.html.erb
<header class = main-header>

  <div class = l-header>
    <h2 class = l-header__logo>エンジニア案件サイト</h2>
  </div>

  <div class = r-header>

    <div class = "r-header__top">
        <form id="form4" action="自分のサイトURL" method="get">
          <input id="sbox4"  id="s" name="s" type="text" placeholder="案件を入力してください" />
          <button id="sbtn4" type="submit">検索</button>
        </form>
    </div>

    <div class = r-header__buttom>
      <li class = r-header__buttom-subitem>
        <%= link_to "案件を探す", matter_index_path, class: "r-header__buttom-subitem-btn" %>
      </li>
      <li class = r-header__buttom-subitem>
        <%= link_to "ログイン", new_user_session_path, class: "r-header__buttom-subitem-btn" %>
      </li>
      <li class = r-header__buttom-subitem>
        <%= link_to "新規登録", new_user_registration_path, class: "r-header__buttom-subitem-btn" %>
      </li>
      <li class = r-header__buttom-subitem>
        <%= link_to "Qiita", new_matter_path, class: "r-header__buttom-subitem-btn" %>
      </li>
    </div>
  </div>

</header>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <%= render 'aftersign_header' %>
  <%= render 'footer' %>
<% else %>
  <%= render 'header' %>
  <%= render 'footer' %>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title EngineerMarket
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/matter/edit.html.erb
<%= render '/home/aftersign_header' %>


<div class = "matter__new">

  <h1 class = "matter__new-title">案件を編集する</h1>

  <%= form_with model: @matter do |f| %>
    
    <%= f.label :name, '案件の名前を入力してください' ,class: :"form_item-title"  %>
    <%= f.text_field :name, placeholder: "田中 太郎" ,class: :"form_item" %>
    
    <%= f.label :price, '案件報酬を入力してください' ,class: :"form_item-title" %>
    <%= f.number_field :price, placeholder: "600000" ,class: :"form_item" %>
    
    <%= f.label :category, '案件での使用言語を入力してください' ,class: :"form_item-title" %>
    <%= f.text_field :category, placeholder: "HTML,CSS,Ruby" ,class: :"form_item" %>
    
    <%= f.label :description, '案件の詳細を入力してください' ,class: :"form_item-title" %>
    <%= f.text_area :description, 
      placeholder: "詳細を入力してください" ,class: :"form_item-description" %>
    
    <%= f.label :filingday, '案件の提出日を入力してください' ,class: :"form_item-title" %>
    <%= f.datetime_field :filingday, class: :"form_item" %>
    
    <%= f.label :skill, '案件での必須スキル・条件を入力してください' ,class: :"form_item-title" %>
    <%= f.text_field :skill, placeholder: "HTML,CSS,Ruby"  ,class: :"form_item" %>

    <%= f.submit "案件を編集する" ,class: :"form_item" %>
    
  <% end %>
</div>


<%= render 'home/footer' %>

app/views/matter/index.html.erb
<% if user_signed_in? %>
  <%= render 'home/aftersign_header' %>

  <div class = content__title>
        <h2 class = midasi><span>最新案件</span></h2>
  </div>

  <div class = "contents">
    <% @matter.each do |matter| %>

      <div class = "content_main">
        
        <a class = "matter__title"><%= matter.name %></a>
        <a class = "matter__price">￥<%= matter.price %>/月</a>
        <a class = "matter"><%= matter.category %></a>
        <a class = "matter">必要スキル：<%= matter.skill %></a>
        <a class = "matter">提出期限日：<%= matter.filingday %></a>
        <% if user_signed_in? && current_user.id == matter.user_id %>
          <%= link_to "編集", edit_matter_path(matter) %>
          <%= link_to "削除", matter, method: :delete, data: { confirm: "#{matter.name}を削除して大丈夫ですか？" } %>
        <% end %>
        <a class = "description"><%= matter.description %></a>
        <%= link_to "案件の詳細を見る", matter_path(matter) %>
      </div>
    <% end %>
  </div>

  <%= render 'home/footer' %>
<% else %>
  <%= render 'home/header' %>

  <div class = content__title>
        <h2 class = midasi><span>最新案件</span></h2>
  </div>

  <div class = "contents">
    <% @matter.each do |matter| %>

      <div class = "content_main">
        
        <a class = "matter__title"><%= matter.name %></a>
        <a class = "matter__price">￥<%= matter.price %>/月</a>
        <a class = "matter"><%= matter.category %></a>
        <a class = "matter">必要スキル：<%= matter.skill %></a>
        <a class = "matter">提出期限日：<%= matter.filingday %></a>

        
        <a class = "description"><%= matter.description %></a>
      </div>
    <% end %>
  </div>

  <%= render 'home/footer' %>
<% end %>

app/views/matter/new.html.erb
<%= render '/home/aftersign_header' %>


<div class = "matter__new">

  <h1 class = "matter__new-title">案件を募集する</h1>

  <%= form_with model: @matter, url: matter_index_path do |f| %>
    
    <%= f.label :name, '案件の名前を入力してください' ,class: :"form_item-title"  %>
    <%= f.text_field :name, placeholder: "田中 太郎" ,class: :"form_item" %>
    
    <%= f.label :price, '案件報酬を入力してください' ,class: :"form_item-title" %>
    <%= f.number_field :price, placeholder: "600000" ,class: :"form_item" %>
    
    <%= f.label :category, '案件での使用言語を入力してください' ,class: :"form_item-title" %>
    <%= f.text_field :category, placeholder: "HTML,CSS,Ruby" ,class: :"form_item" %>
    
    <%= f.label :description, '案件の詳細を入力してください' ,class: :"form_item-title" %>
    <%= f.text_area :description, 
      placeholder: "詳細を入力してください" ,class: :"form_item-description" %>
    
    <%= f.label :filingday, '案件の提出日を入力してください' ,class: :"form_item-title" %>
    <%= f.datetime_field :filingday, class: :"form_item" %>
    
    <%= f.label :skill, '案件での必須スキル・条件を入力してください' ,class: :"form_item-title" %>
    <%= f.text_field :skill, placeholder: "HTML,CSS,Ruby"  ,class: :"form_item" %>

    <%= f.submit "案件を投稿する" ,class: :"form_item" %>
    
  <% end %>
</div>


<%= render 'home/footer' %>

app/views/matter/show.html.erb
<div class = "content_main">    
  <a class = "matter__title"><%= @matter.name %></a>
  <a class = "matter__price">￥<%= @matter.price %>/月</a>
  <a class = "matter"><%= @matter.category %></a>
  <a class = "matter">必要スキル：<%= @matter.skill %></a>
  <a class = "matter">提出期限日：<%= @matter.filingday %></a>
  <% if user_signed_in? && current_user.id == @matter.user_id %>
    <%= link_to "編集", edit_matter_path(@matter) %>
    <%= link_to "削除", @matter, method: :delete, data: { confirm: "#{@matter.name}を削除して大丈夫ですか？" } %>
  <% end %>
  <a class = "description"><%= @matter.description %></a>
</div>